### ISSUE TITLE
`cargo.toml` in `c` directory is detected as duplicate package

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Daniel-Liu-c0deb0t/block-aligner#24]
When including block aligner as a dependency, the file at
https://github.com/Daniel-Liu-c0deb0t/block-aligner/blob/main/c/Cargo.toml
gives this warning:
```
warning: skipping duplicate package `block-aligner` found at `~/.local/share/cargo/git/checkouts/block-aligner-253559227b640923/4014339/c`
```

It's probably best to rename the package to something else there.

**Comment by Daniel-Liu-c0deb0t** [comment]
Yup, noticed this too... I'll rename it to `block-aligner-c` or something else.
