### ISSUE TITLE
`rand_mutate` cannot generate consecutive insertions

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Daniel-Liu-c0deb0t/block-aligner#9]
It seems that `rand_mutate` is slightly limited in the kinds of mutations it can generate, since it decides up front whether to generate a match/substitution/insertion/deletion for each position. This way, it can never insert two or more consecutive characters.

See [this line](https://github.com/Daniel-Liu-c0deb0t/block-aligner/blob/b54c09e0210605bd56c85e950aa9cd1cbf1c1f31/src/simulate.rs#L68): For each generated insertion, it directly pushes the relevant character from `a` after pushing the inserted character.

Something like an insertion followed by a substitution also can't be generated in this model.

Probably this doesn't matter too much in practice, but it's a slight deviation from the common model of generating the mutations one by one, as done in e.g. [wfa](https://github.com/smarco/WFA/blob/750874c70d90a525df1d01413b9010f38f199157/tools/generate_dataset.c#L135).

**Comment by Daniel-Liu-c0deb0t** [comment]
Good point, this is an oversight on my part. I think it does matter in practice because chains of insertions and deletions makes finding the optimal alignment slightly more difficult for block aligner.

**Comment by RagnarGrootKoerkamp** [comment]
One potential benefit here is that the actual edit distance of the generated sequence is probably a bit higher than in the completely uniform model. At least my intuition is that in your code the probability of mutations 'cancelling' each other is smaller.

Anyway, I'll likely write a linear time rust implementation for this soon.

**Comment by RagnarGrootKoerkamp** [comment]
I've just pushed an implementation using ropes [here](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/master/examples/generate_dataset.rs), in case you'd like to reuse it. I'll likely package it separately at some point.

**Comment by Daniel-Liu-c0deb0t** [comment]
Fixed the implementation of the `rand_mutate` function by using a slightly different approach than before.
